// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7XEZ4FfJPu_burHWDuaat-j_9mPNfmKE',
    appId: '1:214232059358:web:35b506687b814d20cfe14f',
    messagingSenderId: '214232059358',
    projectId: 'drapeau-vert-app',
    authDomain: 'drapeau-vert-app.firebaseapp.com',
    storageBucket: 'drapeau-vert-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCo0OXFHjAyxBLOyaALGhIGfv65oK9_PQQ',
    appId: '1:214232059358:android:e49e0f79d523c9ffcfe14f',
    messagingSenderId: '214232059358',
    projectId: 'drapeau-vert-app',
    storageBucket: 'drapeau-vert-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd2e7heJXhfcRkFZQF1URF5WBWlmtn-P4',
    appId: '1:214232059358:ios:9a83cdf18ade71a0cfe14f',
    messagingSenderId: '214232059358',
    projectId: 'drapeau-vert-app',
    storageBucket: 'drapeau-vert-app.firebasestorage.app',
    iosBundleId: 'com.example.dvcrAppli',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAd2e7heJXhfcRkFZQF1URF5WBWlmtn-P4',
    appId: '1:214232059358:ios:9a83cdf18ade71a0cfe14f',
    messagingSenderId: '214232059358',
    projectId: 'drapeau-vert-app',
    storageBucket: 'drapeau-vert-app.firebasestorage.app',
    iosBundleId: 'com.example.dvcrAppli',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7XEZ4FfJPu_burHWDuaat-j_9mPNfmKE',
    appId: '1:214232059358:web:228cebea051336f1cfe14f',
    messagingSenderId: '214232059358',
    projectId: 'drapeau-vert-app',
    authDomain: 'drapeau-vert-app.firebaseapp.com',
    storageBucket: 'drapeau-vert-app.firebasestorage.app',
  );
}
